spring:
  profiles:
    active: local
  batch:
    job:
      names: ${job.name:NONE}

---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:23306/batch?serverTimezone=UTC&characterEncoding=UTF-8
      username: order-svc
      password: order-pass
  jpa:
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: none
  batch:
    jdbc:
      initialize-schema: always
---
spring:
  config:
    activate:
      on-profile: test
  jpa:
    database: h2